spring:
  redis:
    host:  my-redis  # или IP вашего Redis-сервера
    port: 6379       # стандартный порт Redis
    password: root
    database: 0      # номер базы данных (по умолчанию 0)
    timeout: 5000    # таймаут подключения (мс)
    lettuce:         # настройки пула соединений (Lettuce - клиент по умолчанию)
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  kafka:
    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: my-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: "org.example.mscard.dto" # Укажите пакет DTO
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true  # Критически важная настройка
        spring.json.trusted.packages: "com.example.demo.dto"
  application:
    name: db_cardsdb
  datasource:
    url: jdbc:mysql://my-mysql:3306/cardsdb
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true
server:
  port: 4444